services:
  backend:
    volumes:
      - ./dockerdata/certs:/etc/letsencrypt
      - webrootFiles:/.well-known/acme-challenge:ro
    environment:
      USE_HTTPS: "true"
      HTTPS_DOMAIN: ${HTTPS_DOMAIN}

  letsencrypt:
    build: ./certutil
    restart: always
    volumes:
      - ./dockerdata/certs:/home/work/certs
      - webrootFiles:/var/www/.well-known/acme-challenge
    environment:
      EMAIL: ${HTTPS_EMAIL}
      DOMAIN: ${HTTPS_DOMAIN}
    depends_on:
      - backend
 
volumes:
  webrootFiles:
