services:
  backend:
    build: ./backend
    restart: always
    ports:
      - "80:80"
    volumes:
      - frontendDist:/home/work/frontend
      - ./dockerdata/images:/home/work/images
      - ./${FIREBASEADMINSDK_SECRETKEY_FILENAME}:/home/work/firebaseSecretKey.json
    environment:
      DBADDRESS: postgres://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      OAUTHALLOWDOMAIN: ${OAUTH_ALLOWED_EMAIL_DOMAIN}
    depends_on:
      db:
        condition: service_healthy
      frontend:
        condition: service_completed_successfully

  db:
    image: "postgres:16.4-alpine3.20"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./dockerdata/dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    volumes:
      - frontendDist:/home/work/dist
    environment:
      OAUTH_ALLOWED_EMAIL_DOMAIN: ${OAUTH_ALLOWED_EMAIL_DOMAIN}
      FIREBASE_API_KEY: ${FIREBASE_API_KEY}
      FIREBASE_AUTH_DOMAIN: ${FIREBASE_AUTH_DOMAIN}
      FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID}
      FIREBASE_STORAGE_BUCKET: ${FIREBASE_STORAGE_BUCKET}
      FIREBASE_MESSAGING_SENDER_ID: ${FIREBASE_MESSAGING_SENDER_ID}
      FIREBASE_APP_ID: ${FIREBASE_APP_ID}

volumes:
  frontendDist:
